blank_issues_enabled: true
contact_links:
  - name: 📧 Contact Maintainers
    url: https://nokodo.net/about
    about: Get in touch with the nokodo team
  - name: 💬 Discussions
    url: https://github.com/nokodo-labs/monorepo-template/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/nokodo-labs/monorepo-template/wiki
    about: Access the project's documentation
  - name: 🚀 Releases
    url: https://github.com/nokodo-labs/monorepo-template/releases
    about: View the project's releases
