name: 'Close stale issues and PRs'

on:
  schedule:
    - cron: '0 2,14 * * *'
  issues:
    types: [labeled, unlabeled, edited] #, demilestoned, locked, unlocked, reopened, unassigned]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [labeled, unlabeled, edited] #, locked, unlocked, reopened, unassigned, review_requested, review_request_removed]
  #pull_request_review_comment:
  #  types: [created, edited]
  workflow_dispatch:


permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          stale-issue-message: 'This issue is stale because it has been open 45 days with no activity. Remove stale label, comment or mark with Backlog priority, or this will be closed in 14 days.'
          stale-pr-message: 'This PR is stale because it has been open 60 days with no activity. Remove stale label, comment or mark with Backlog priority, or this will be closed in 21 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 14 days with no activity, and was not marked with Backlog priority.'
          close-pr-message: 'This PR was closed because it has been stalled for 21 days with no activity, and was not marked with Backlog priority.'
          days-before-issue-stale: 45
          days-before-pr-stale: 60
          days-before-issue-close: 14
          days-before-pr-close: 21
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-issue-labels: 'P5 - Backlog'