name: Deploy Frontend to GitHub Pages

on:
  workflow_call:
    inputs:
      vite_api_url:
        description: "API URL to embed at build time (optional)"
        required: false
        type: string
        default: ""
      environment:
        description: "Deployment environment name"
        required: false
        type: string
        default: "github-pages"
    secrets: {}
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: frontend/.nvmrc
          check-latest: true
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          VITE_API_URL: ${{ inputs.vite_api_url || '' }}
          VITE_PAGES: "true"
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Comment PR with preview URL
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v8
        with:
          script: |
            const url = core.getInput('url') || (process.env.DEPLOY_URL || '${{ steps.deployment.outputs.page_url }}');
            const body = `🚀 Preview deployed to: ${url}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body,
            });
        env:
          DEPLOY_URL: ${{ steps.deployment.outputs.page_url }}
