name: Frontend CI

on:
  workflow_call:
  workflow_dispatch:

jobs:
  quality:
    name: Frontend Quality (Node ${{ matrix.node_version }})
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.node_version != '24.10' }}
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - "24.10"
          - "24"
    defaults:
      run:
        shell: bash
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Check formatting
        run: npm run format

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run check

      - name: Build
        run: npm run build
