name: Frontend CI

on:
  workflow_call:
    inputs:
      run_tests:
        description: "whether to run tests"
        type: boolean
        required: false
        default: true
      run_lint:
        description: "whether to run linting"
        type: boolean
        required: false
        default: false
  workflow_dispatch:
    inputs:
      run_tests:
        description: "whether to run tests"
        type: boolean
        required: false
        default: true
      run_lint:
        description: "whether to run linting"
        type: boolean
        required: false
        default: false

jobs:
  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: frontend/.nvmrc
          check-latest: true
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format

  quality:
    name: Check Quality on Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    needs: format
    strategy:
      fail-fast: false
      matrix:
        node:
          - file
          - "25"
    continue-on-error: ${{ matrix.node != 'file' }}
    defaults:
      run:
        shell: bash
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node from .nvmrc
        if: ${{ matrix.node == 'file' }}
        uses: actions/setup-node@v6
        with:
          node-version-file: frontend/.nvmrc
          check-latest: true
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Setup Node ${{ matrix.node }}
        if: ${{ matrix.node != 'file' }}
        uses: actions/setup-node@v6
        with:
          node-version: "${{ matrix.node }}"
          check-latest: true
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        if: ${{ inputs.run_lint }}
        run: npm run lint

      - name: Type check
        run: npm run check

      - name: Run tests
        if: ${{ inputs.run_tests }}
        run: npm run test

      - name: Build
        run: npm run build
